# Generated by Django 4.2.29 on 2026-03-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryorder",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="inventory/docs/"),
        ),
        migrations.AddField(
            model_name="internaltransfer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="inventory/docs/"),
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="inventory/docs/"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="inventory/docs/"),
        ),
    ]
